<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>file-watcher.output</string>
        <key>name</key>
        <string>file-watcher-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                     <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[(?:onFolderChange|onFolderCreate|onFolderDelete)\]).*(\".+\")</string>
                <key>name</key>
                <string>file-watcher.folderChange</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[(?:onFileChange|onFileChangeImmediate|onFileRename|onFileDelete|onFileCreate)\]).*(\".+\")</string>
                <key>name</key>
                <string>file-watcher.fileChange</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.warn-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.warn-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[(?:cmd|vscode-task)\])(.*)</string>
                <key>name</key>
                <string>file-watcher.cmd</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\[(?i:(Down|Error|Failure|Fail|Fatal))\]</string>
                <key>name</key>
                <string>token.error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\[Config reloaded\]</string>
                <key>name</key>
                <string>token.info-token</string>
            </dict>
        </array>
    </dict>
</plist>